runtime: python37
env: standard
# api_version: 1
# threadsafe: true
# service: core
service: test

# entrypoint: gunicorn -b :$PORT main:app
# entrypoint: gunicorn <main:app> --bind 0.0.0.0:8080 --worker-class sanic.worker.GunicornWorker
entrypoint: gunicorn main:app --bind 0.0.0.0:8080 --worker-class sanic.worker.GunicornWorker
# entrypoint: python main.py

handlers:
- url: /static
  static_dir: dist/static/
- url: /.*
  script: auto

env_variables:
  AX_VERSION: 0.1.0
  # AX_HOST: 0.0.0.0 #  default = 127.0.0.1
  # AX_PORT: "8085" #  default = 8080
  # AX_SANIC_DEBUG: true #  default=false
  # AX_SANIC_ACCESS_LOG:  #  default=false
  # AX_CACHE_MODE: "" # ' default='default'. Set 'redis' for redis
  # AX_REDIS_ENDPOINT:  #  default='127.0.0.1'
  # AX_REDIS_PORT:  #  default='6379'
  # AX_REDIS_TIMEOUT:  #  default='1'
  AX_TIMEZONE: Europe/Moscow #  default=UTC
  AX_LOGS_LEVEL: DEBUG # ERROR, WARNING, INFO, DEBUG. default = ERROR
  # AX_LOGS_FILENAME: ax_logs.log #  If not set, logs only output to stdio
  # AX_LOGS_ABSOLUTE_PATH: 'D:\Projects\' #  default =
  AX_DB_REVISION: v0.0.11_2b12003a3b8
  # AX_DB_DIALECT: # sqlite, postgre, mysql. Default is sqlite
  # AX_DB_HOST:
  # AX_DB_PORT:
  # AX_DB_LOGIN:
  # AX_DB_PASSWORD:
  # AX_DB_DATABASE:
  # AX_DB_SQLITE_FILENAME: "my_ax.db" #  default='ax_sqlite.db
  AX_DB_SQLITE_ABSOLUTE_PATH: "/tmp" #  default=None
  AX_LOCALE: ru # default=en
  AX_TMP_ABSOLUTE_PATH: '/tmp' #'D:\Projects\tmp'
  AX_UPLOADS_ABSOLUTE_PATH: '/tmp/uploads'
