runtime: python37
env: standard
# api_version: 1
# threadsafe: true
# service: core
service: test

# entrypoint: gunicorn -b :$PORT main:app
# entrypoint: gunicorn <main:app> --bind 0.0.0.0:8080 --worker-class sanic.worker.GunicornWorker
entrypoint: gunicorn main:app --bind 0.0.0.0:8080 --worker-class sanic.worker.GunicornWorker
# entrypoint: python main.py

handlers:
- url: /static
  static_dir: dist/static/
- url: /.*
  script: auto

env_variables:
  AX_VERSION: 0.8.0
  # AX_HOST: 0.0.0.0 #  default = 127.0.0.1
  # AX_PORT: "8085" #  default = 8080
  # AX_SANIC_DEBUG: true #  default=false
  # AX_SANIC_ACCESS_LOG:  #  default=false
  # AX_CACHE_MODE: "" # ' default='default'. Set 'redis' for redis
  # AX_REDIS_ENDPOINT:  #  default='127.0.0.1'
  # AX_REDIS_PORT:  #  default='6379'
  # AX_REDIS_TIMEOUT:  #  default='1'
  AX_TIMEZONE: Europe/Moscow #  default=UTC
  AX_LOGS_LEVEL: DEBUG # ERROR, WARNING, INFO, DEBUG. default = ERROR
  # AX_LOGS_FILENAME: ax_logs.log #  If not set, logs only output to stdio
  # AX_LOGS_ABSOLUTE_PATH: 'D:\Projects\' #  default =
  AX_DB_REVISION: 9b898740929f

  # AX_DB_DIALECT: 'postgre' # sqlite, postgre, mysql. Default is sqlite
  # AX_DB_HOST: '127.0.0.1'
  # AX_DB_PORT: '5432'
  # AX_DB_LOGIN: 'postgres'
  # AX_DB_PASSWORD: 'Cnuds644'
  # AX_DB_DATABASE: 'wine'


  AX_DB_DIALECT: postgre   # sqlite, postgre, mysql. Default is sqlite
  AX_DB_HOST: 84.201.174.246
  AX_DB_PORT: '5432'
  AX_DB_LOGIN: postgres
  AX_DB_PASSWORD: Sdgs2019
  AX_DB_DATABASE: wine

  # AX_DB_SQLITE_FILENAME: "wine.db" #  default='ax_sqlite.db
  # AX_DB_SQLITE_ABSOLUTE_PATH: "C:\\Users\\enf64_000\\Desktop\\Dimiant\\WineProject\\Archive" #  default=None

  # AX_LOCALE: ru # default=en
  # AX_TMP_ABSOLUTE_PATH: '/tmp' #'D:\Projects\tmp'
  # AX_UPLOADS_ABSOLUTE_PATH: '/tmp/uploads'
